### PR TITLE
Transformations are derived from image headers

### PR DESCRIPTION
**Pull request by machow**
Okay, I finally got around to starting on the changes. I figured it would be useful to get everything working, and then make fine grained changes (e.g. how to set a reference header) after. The gist of what I've done so far is..
- remove the only call to `Transform` from view.coffee, relying on a new (convenience) method in app.coffee for now.
- transforms in Image instantiations are now ndarrays
- LayerList now can make a layer the reference layer

The last part is to use the images to do the transformations. The snag I've run into is that it seems that there are two cases where Transform.xToY() is used.
1. before images are loaded, as in the constructor of the Viewer class (in app.coffee)
2. after images are loaded, when it makes sense to pass a reference image

Do you have a sense for when the first case is being used, and whether we can defer those until images have been loaded? I can make sourcemaps and look more closely sort it out, but figured I'd check first. I added an image argument to Transform.atlasToImage and imageToAtlas in the most recent commit, but need to make some more changes before it will run.

### CODE REVIEW

**Comment by tyarkoni** [comment]
Hi Michael,

Great! I'm currently out of town and not able to take a look at this until Friday, so if you don't mind, I'll hold off merging until then. But I'm excited to look at it, and your overview of the changes sounds great to me! I don't remember off-hand where the transformation calls are being made (or why), but will take a look at that as well when I can. Thanks!

**Comment by machow** [comment]
That sounds good. Once I hear back about Transform, or get some time to dig a bit deeper, I can try implementing the rest of the changes.

**Comment by tyarkoni** [comment]
Thanks for the reminder. I took a look and it all looks good, but images that don't have dims [91, 109, 91] are currently not loading properly (at least, the one I tried didn't--I grabbed a random image from NeuroVault that displayed fine on the website); the image gets read in, but the orientation must  be off because voxels are in the wrong places. Not sure if this is because you hadn't gotten to that yet, or if it's something we should look at (possibly an issue in xtk).

Re: the transform call in the constructor, I think that might just be for purposes of rendering the crosshairs in the right place, or something like that. I don't think it will hurt to drop it and move it to the paint call--that's where it should be anyway. But I guess we can try it and see what happens. Let me know if that answers your question. Thanks again!

Oh, as a side note, see #25... @njvack has a working prototype of a pretty neat and blazingly fast reader/renderer. We should probably switch at some point, as it would alleviate all the xtk overhead and already seems to parse headers appropriately. I'm hoping to have some time to look at what that would involve in a couple of weeks, but feel free to check it out and see if you think it's feasible. If it does look straightforward to integrate, it might not be worth investing more effort making the current solution work.

**Comment by machow** [comment]
sorry I lost track of this--cleaning up PRs :)

**Pull request closed without merging**
