### PR TITLE
rebuilt xtk with less minification

### PR DESCRIPTION
**Pull request by machow**
The transformation matrices can now be accessed as `volume_name._RASToIJK` and vice-versa. I looked at the transformations being made in `app.coffee`, and it seems like there are a couple options here for generalizing the transformations.

1. Ensure all images have the same dimensions and use the same transformations for all layers (dependent on, say, the first layer loaded). Could add volume argument to transformation functions.

2. Make Transformation a coffeescript class that takes a volume and stores correct matrices as attributes. Instantiate a new transformation object for each layer. Use one of them (a reference layer) for many of the transformations in `app.coffee`.

I feel like there's a hitch with the second option that I'm not realizing, so lean toward the first. I'm happy to take a stab at implementing it when I can find some time.

### CODE REVIEW

**Comment by tyarkoni** [comment]
We had a discussion about the first issue you raise at the OHBM hackathon last year in Berlin--i.e., whether all layers should be forced to have the same dimensionality as the first loaded layer (the way, e.g., FSL does it), or basically pass the buck to the user and allow any image to be rendered as long as it has a mapping onto the anatomical underlay. I think the conclusion was somewhere in between, where the idea would be that the first image loaded (typically the anatomical underlay) defines the mapping between the world and the canvas, and sets the boundaries of the world grid, but doesn't prevent you from loading images in other spaces. So, for example, say you load an anatomical image that defines a bounding box of (say) 20 cm^3, which then gets mapped onto the dimensions of the current canvas. If you then load another image that stipulates a 30 cm box but has the same origin, the edges of the new image will get cut off, but the values inside the original box will still be displayed appropriately. This way you have the flexibility of loading virtually any image, while passing the responsibility of ensuring that things makes sense onto the user.

That still leaves the implementation question. I like the idea of having a Transform class that gets instantiated anew for each loaded layer, and don't immediately see any major downside to doing it that way. I guess one could argue that it's overkill, since technically the images only need to store the transformation matrices; the actual transformation operation is just a matrix multiplication that's currently implemented in Transform.transformCoordinates in models.coffee. In any case, feel free to take a stab at it any which way you like; but if you don't mind waiting a day or two, I'll probably spend some time thinking about it a bit more, as I think there are some peculiarities of the current implementation that we should probably work through rather than around.

**Comment by machow** [comment]
I think the Transform class will also need to make the transformation matrices to canvas view, which should be straightforward, but might be a point in favor of keeping it around. 

Sitting on it for few days sounds good!

**Comment by njvack** [comment]
This is perhaps off-topic for this PR, but I think that if we change out the rendering engine to be based on webgl instead of canvas, allowing layers in arbitrary spaces (as long as we can map them all to the same world coordinates) would be trivial.

Back when neurosynth was new, webgl support wasn't ubiquitous enough, probably, for that to be feasible, but it probably would make sense now.

**Comment by tyarkoni** [comment]
Agreed, @njvack, I think we're at the point where we could safely switch to webgl without losing more than 2 - 3% of the users (and maybe that might prompt them to install a modern browser). That said, I'm not sure that would solve the space issue. In principle we could also allow each unique space to map freely onto the current html5 canvas; the problem (unless I'm missing something) is that it would look terrible, and probably confusing--which would still be true with webgl.

My other reservation with webgl is that, given that we're doing pure 2D rendering of orthviews (I don't have any plans to move to 3D), I'm not sure there's a real benefit to switching. There are a lot of major performance optimizations that could be done prior to the rendering step (I'm planning to open issues for some of them), and if we do things correctly, html5 should have no trouble maintaining adequate performance even with many loaded layers. (E.g., the biggest issue is that right now every layer is painted independently, whereas it would make much more sense to pre-compute the final color by summing over all active layers, and only paint once. That alone should dramatically boost performance.)

In any case, ideally we should really decouple the data model from the rendering entirely, so I do think that even if we end up keeping canvas as the rendering engine, we may want to modularize things a bit to pave the way for other renderers.

**Comment by njvack** [comment]
I think the big thing that webgl would make easier to solve would be display of data with different alignments or voxel sizes -- for example 2mm stats on 1mm anatomy, or stats on an oblique slice plane. It wouldn't be too terrible to do this with arrays and canvas, but we'd need to implement our own resampling algorithm.

Agreed that non-orthoviews aren't particularly compelling.

**Pull request merged**
